### ISSUE TITLE
Use within iOS App

### ISSUE THREAD

**Issue by marlowcharite** [kenshiro-o/RapGenius-JS#7]
Hey guys. I'm currently developing an iOS application that I need to pull lyrics for songs that I specify. I'm currently researching different apis that I can use to retrieve song lyrics. How can I use this within my iOS application? Thanks

**Comment by kenshiro-o** [comment]
Hey @marlowcharite. Wow that's a late reply. Sorry I have not maintained this project very well.
Please use this api I created about a year ago: http://genius-api.com/ . It exposes a few REST endpoints so I hope it will do the job just fine.
